/*
 * Space Cowboy — Service Worker (PR 2, Subtask P0.3)
 * ---------------------------------------------------
 * Goal: cache-first repeat visits. Target on 2nd visit:
 *   - TTI < 500 ms, total network < 500 KB.
 *
 * Cache name: 'space-cowboy-v16'. Bump the version suffix when the cache
 * contract changes — and ALWAYS when a file under ./vendor/ or ./textures/
 * is edited in place (those are cache-first AND skipped by install when
 * already stored, so without a bump returning players keep the old copy
 * indefinitely — Ipad.md §7 trap 1, the placebo update).
 *
 * Routing strategy (GET requests only — all other methods pass through):
 *
 *   NETWORK-FIRST (so new deploys take effect on the next visit, not the
 *   next-next visit; falls back to cache, then a synthetic offline Response):
 *     - HTML navigations (`request.mode === 'navigate'` OR Accept ~ text/html)
 *     - JS modules (URL pathname ends in .js or .mjs)
 *
 *   CACHE-FIRST (immutable / large blobs / vendor code — fetch from cache
 *   if present, otherwise hit the network and populate the cache):
 *     - Anything under `/vendor/` (Three.js + addons, vendored same-origin)
 *     - Anything under `/textures/`
 *     - Anything under `/data/`
 *
 *   PASS-THROUGH for anything else.
 *
 * Three.js is served same-origin from `./vendor/` (no CDN). The sim is
 * fully offline-first when served from any static host; the only hard limit
 * is that browsers bypass the service worker on a force-refresh, so offline
 * hard-refresh works when a local server is running (localhost serves
 * everything) but on a remote deploy a hard-refresh needs the network — a
 * normal reload is the offline path there.
 *
 * Scope: this file lives at the workspace root and is registered from
 * index.html via the relative path `./sw.js`, so the scope is the page
 * directory by default. Locally that is `/`; on GitHub Pages it is `/SCB/`.
 * Do NOT hard-code `/SCB/` — all paths in this file are relative.
 *
 * The SW does not intercept its own URL (we never call respondWith for it).
 */

const CACHE_NAME = 'space-cowboy-v16';

// ---------------------------------------------------------------------------
// PRECACHE MANIFEST — offline permanence (iPad port Phase 2, Ipad.md §2.4).
// Every runtime file is precached at install so the home-screen WebClip keeps
// booting with the cable unplugged, forever. Textures are capped at the 8k
// tier (no *_16k.*) — glass clamps its LOD to 8k (Earth.js clampLODForGlass),
// so the capped set is exactly what a touch device requests.
//
// The block between the >>> / <<< markers is GENERATED by
// scripts/build-precache.mjs (chained into the cable serve). Never edit it by
// hand — regenerate it. PRECACHE_BUILD makes this file byte-different per
// build, which is what triggers the SW update → install → re-precache cycle
// on the next cabled load (update honesty stays with the corner hash).
// >>> PRECACHE-MANIFEST (generated by scripts/build-precache.mjs — do not edit)
const PRECACHE_BUILD = "c39d3e445fb67";
const PRECACHE_URLS = [
  "./",
  "./data/META.json",
  "./data/active-sats.json",
  "./data/build-tag.json",
  "./data/cities.json",
  "./data/codex.json",
  "./data/constellations.json",
  "./data/debris-catalog.json",
  "./data/ground-stations.json",
  "./data/launches.json",
  "./data/news-events.json",
  "./data/space-weather.json",
  "./icon-180.png",
  "./index.html",
  "./js/core/BlackFrameProbe.js",
  "./js/core/Constants.js",
  "./js/core/DevShotGate.js",
  "./js/core/EventBus.js",
  "./js/core/Events.js",
  "./js/core/FloorContract.js",
  "./js/core/GameState.js",
  "./js/core/Languages.js",
  "./js/core/ProfileFlags.js",
  "./js/core/StorageKeys.js",
  "./js/core/VisualLaw.js",
  "./js/core/ZoomLadder.js",
  "./js/core/dataUrl.js",
  "./js/core/daughterNames.js",
  "./js/core/missionProgress.js",
  "./js/data/blueprintSubsystems.js",
  "./js/dev/FlickTraceRecorder.js",
  "./js/dev/flickSweepCore.js",
  "./js/entities/ActiveSatellite.js",
  "./js/entities/ArmDockBasis.js",
  "./js/entities/ArmManager.js",
  "./js/entities/ArmUnit.js",
  "./js/entities/BridleRing.js",
  "./js/entities/CaptureNet.js",
  "./js/entities/CatalogConverter.js",
  "./js/entities/DebrisField.js",
  "./js/entities/FieldRiskModel.js",
  "./js/entities/InsertionPlanner.js",
  "./js/entities/LaunchWindow.js",
  "./js/entities/OrbitalMechanics.js",
  "./js/entities/PlayerSatellite.js",
  "./js/entities/ReachabilityModel.js",
  "./js/entities/armPlumeModel.js",
  "./js/entities/debrisFerrous.js",
  "./js/main.js",
  "./js/scene/CityLabels.js",
  "./js/scene/Earth.js",
  "./js/scene/Ephemeris.js",
  "./js/scene/LaunchCameo.js",
  "./js/scene/LaunchCinematic.js",
  "./js/scene/NearFieldRenderPass.js",
  "./js/scene/SceneManager.js",
  "./js/scene/Starfield.js",
  "./js/scene/SunLight.js",
  "./js/scene/TierVisualManager.js",
  "./js/scene/avionicsMaterials.js",
  "./js/scene/bodyCatalog.js",
  "./js/scene/bodyGeometry.js",
  "./js/scene/detailLodCull.js",
  "./js/scene/glowSpriteTexture.js",
  "./js/scene/labelTexture.js",
  "./js/scene/mliFoilTexture.js",
  "./js/scene/nearFieldMath.js",
  "./js/scene/orbitalFoilEnv.js",
  "./js/scene/plumeGeometry.js",
  "./js/scene/plumeRibbon.js",
  "./js/scene/railOrder.js",
  "./js/scene/solarCellTexture.js",
  "./js/scene/starCatalog.js",
  "./js/scene/sunStaging.js",
  "./js/systems/ActiveSatGuard.js",
  "./js/systems/AimDecomposition.js",
  "./js/systems/AmbientLaunchScheduler.js",
  "./js/systems/ArchiveFloor.js",
  "./js/systems/ArmIdleAdvisor.js",
  "./js/systems/ArmTierCatalog.js",
  "./js/systems/AudioSystem.js",
  "./js/systems/AutoLockController.js",
  "./js/systems/AutoProfileSweep.js",
  "./js/systems/AutopilotSystem.js",
  "./js/systems/CameraSystem.js",
  "./js/systems/CargoSystem.js",
  "./js/systems/CatalogLoader.js",
  "./js/systems/CeremonyTimeScale.js",
  "./js/systems/CoMCalculator.js",
  "./js/systems/CodexSystem.js",
  "./js/systems/CollisionAvoidanceSystem.js",
  "./js/systems/CommsSystem.js",
  "./js/systems/ConjunctionSystem.js",
  "./js/systems/DespinLaser.js",
  "./js/systems/DevSequenceAdvancer.js",
  "./js/systems/DossierSystem.js",
  "./js/systems/EnvironmentSystem.js",
  "./js/systems/ForgeSystem.js",
  "./js/systems/GameFlowManager.js",
  "./js/systems/GpuProbe.js",
  "./js/systems/GuidanceDirector.js",
  "./js/systems/GuidanceTelemetry.js",
  "./js/systems/HullCamFloor.js",
  "./js/systems/InputManager.js",
  "./js/systems/IssConjunctionBoss.js",
  "./js/systems/KesslerSystem.js",
  "./js/systems/LadderAudioBeds.js",
  "./js/systems/LadderController.js",
  "./js/systems/LassoSystem.js",
  "./js/systems/LaunchSequence.js",
  "./js/systems/MenuOrbitPreview.js",
  "./js/systems/MissionCoach.js",
  "./js/systems/MissionEventSystem.js",
  "./js/systems/MissionMilestones.js",
  "./js/systems/MoidCalculator.js",
  "./js/systems/NavRecoveryAdvisor.js",
  "./js/systems/NavcomFloor.js",
  "./js/systems/OnboardingDirector.js",
  "./js/systems/PersistenceManager.js",
  "./js/systems/PowerDistribution.js",
  "./js/systems/ProxNetFloor.js",
  "./js/systems/QualityManager.js",
  "./js/systems/ReputationSystem.js",
  "./js/systems/ResourceSystem.js",
  "./js/systems/RewardSystem.js",
  "./js/systems/ScoringSystem.js",
  "./js/systems/SdaFloor.js",
  "./js/systems/SensorSystem.js",
  "./js/systems/SettingsManager.js",
  "./js/systems/SkillsSystem.js",
  "./js/systems/SpaceWeatherSystem.js",
  "./js/systems/StarlinkCascadeBoss.js",
  "./js/systems/SubsystemEvents.js",
  "./js/systems/TargetAcquisition.js",
  "./js/systems/TargetSelector.js",
  "./js/systems/TeachingSystem.js",
  "./js/systems/TetherReel.js",
  "./js/systems/TimeAuthority.js",
  "./js/systems/TimerManager.js",
  "./js/systems/ToolOdds.js",
  "./js/systems/ToolRecommender.js",
  "./js/systems/TrawlManager.js",
  "./js/systems/WheelRouter.js",
  "./js/systems/_beatLifecycle.js",
  "./js/systems/_bossLifecycle.js",
  "./js/systems/audio/soundVocabulary.js",
  "./js/systems/codex/GlossaryState.js",
  "./js/systems/codex/codexData.js",
  "./js/systems/codex/codexInterpolate.js",
  "./js/systems/codex/codexTriggers.js",
  "./js/systems/codex/egoLayout.js",
  "./js/systems/codex/glossary.js",
  "./js/systems/collisionModel.js",
  "./js/systems/commsSuppression.js",
  "./js/systems/netRouting.js",
  "./js/systems/startOrbitMath.js",
  "./js/systems/upgradeEffectRoutes.js",
  "./js/ui/BlueprintOverlay.js",
  "./js/ui/BriefingScreen.js",
  "./js/ui/CaptureNetVisual.js",
  "./js/ui/ClusterIcons.js",
  "./js/ui/CodexViewerUI.js",
  "./js/ui/DaughterWireframe.js",
  "./js/ui/DebrisMap.js",
  "./js/ui/DebrisTextureAtlas.js",
  "./js/ui/DebrisWireframe.js",
  "./js/ui/DebugOverlay.js",
  "./js/ui/DockingReticle.js",
  "./js/ui/FlagDecalSystem.js",
  "./js/ui/FurnaceBreakdownVisual.js",
  "./js/ui/GameOverScreen.js",
  "./js/ui/HUD.js",
  "./js/ui/HotkeyOverlay.js",
  "./js/ui/MenuScene3D.js",
  "./js/ui/MenuScreen.js",
  "./js/ui/MotherCallouts.js",
  "./js/ui/NavSphere.js",
  "./js/ui/NetMeshKit.js",
  "./js/ui/OrbitMFD.js",
  "./js/ui/PerfReportOverlay.js",
  "./js/ui/ProxContextPanel.js",
  "./js/ui/ProxMiniSphere.js",
  "./js/ui/ProxOverlay.js",
  "./js/ui/RailIndicator.js",
  "./js/ui/ReachOrb.js",
  "./js/ui/SdaChart.js",
  "./js/ui/ShopScreen.js",
  "./js/ui/StrategicMap.js",
  "./js/ui/SweepReportUI.js",
  "./js/ui/TargetReticle.js",
  "./js/ui/TeachingOverlay.js",
  "./js/ui/TouchControls.js",
  "./js/ui/TrailSystem.js",
  "./js/ui/TransferWindows.js",
  "./js/ui/VelocityStreaks.js",
  "./js/ui/glossaryDom.js",
  "./js/ui/hud/CommsPanel.js",
  "./js/ui/hud/HintTicker.js",
  "./js/ui/hud/NetInventoryPanel.js",
  "./js/ui/hud/PaneChrome.js",
  "./js/ui/hud/PaneDensity.js",
  "./js/ui/hud/SkillsPane.js",
  "./js/ui/hud/StatusPanel.js",
  "./js/ui/hud/StrutLabels.js",
  "./js/ui/hud/TargetPanel.js",
  "./js/ui/hudPulse.js",
  "./js/ui/menuActions.js",
  "./js/ui/shopGating.js",
  "./js/ui/shopPin.js",
  "./js/ui/touchTelemetry.js",
  "./js/ui/viewCover.js",
  "./textures/earth_clouds.avif",
  "./textures/earth_clouds.jpg",
  "./textures/earth_clouds_8k.avif",
  "./textures/earth_clouds_8k.jpg",
  "./textures/earth_day.avif",
  "./textures/earth_day.jpg",
  "./textures/earth_day_8k.avif",
  "./textures/earth_day_8k.jpg",
  "./textures/earth_night.avif",
  "./textures/earth_night.jpg",
  "./textures/earth_night_8k.avif",
  "./textures/earth_night_8k.jpg",
  "./textures/eva-astronaut.png",
  "./textures/mli_foil_albedo.png",
  "./textures/mli_foil_flat_albedo.png",
  "./textures/mli_foil_flat_normal.png",
  "./textures/mli_foil_flat_roughness.png",
  "./textures/mli_foil_normal.png",
  "./textures/mli_foil_roughness.png",
  "./textures/mli_foil_roughness_small.png",
  "./vendor/three/build/three.core.js",
  "./vendor/three/build/three.module.js",
  "./vendor/three/examples/jsm/environments/ColorEnvironment.js",
  "./vendor/three/examples/jsm/environments/DebugEnvironment.js",
  "./vendor/three/examples/jsm/environments/RoomEnvironment.js",
  "./vendor/three/examples/jsm/lines/Line2.js",
  "./vendor/three/examples/jsm/lines/LineGeometry.js",
  "./vendor/three/examples/jsm/lines/LineMaterial.js",
  "./vendor/three/examples/jsm/lines/LineSegments2.js",
  "./vendor/three/examples/jsm/lines/LineSegmentsGeometry.js",
  "./vendor/three/examples/jsm/lines/Wireframe.js",
  "./vendor/three/examples/jsm/lines/WireframeGeometry2.js",
  "./vendor/three/examples/jsm/lines/webgpu/Line2.js",
  "./vendor/three/examples/jsm/lines/webgpu/LineSegments2.js",
  "./vendor/three/examples/jsm/lines/webgpu/Wireframe.js",
  "./vendor/three/examples/jsm/postprocessing/AfterimagePass.js",
  "./vendor/three/examples/jsm/postprocessing/BloomPass.js",
  "./vendor/three/examples/jsm/postprocessing/BokehPass.js",
  "./vendor/three/examples/jsm/postprocessing/ClearPass.js",
  "./vendor/three/examples/jsm/postprocessing/CubeTexturePass.js",
  "./vendor/three/examples/jsm/postprocessing/DotScreenPass.js",
  "./vendor/three/examples/jsm/postprocessing/EffectComposer.js",
  "./vendor/three/examples/jsm/postprocessing/FXAAPass.js",
  "./vendor/three/examples/jsm/postprocessing/FilmPass.js",
  "./vendor/three/examples/jsm/postprocessing/GTAOPass.js",
  "./vendor/three/examples/jsm/postprocessing/GlitchPass.js",
  "./vendor/three/examples/jsm/postprocessing/HalftonePass.js",
  "./vendor/three/examples/jsm/postprocessing/LUTPass.js",
  "./vendor/three/examples/jsm/postprocessing/MaskPass.js",
  "./vendor/three/examples/jsm/postprocessing/OutlinePass.js",
  "./vendor/three/examples/jsm/postprocessing/OutputPass.js",
  "./vendor/three/examples/jsm/postprocessing/Pass.js",
  "./vendor/three/examples/jsm/postprocessing/RenderPass.js",
  "./vendor/three/examples/jsm/postprocessing/RenderPixelatedPass.js",
  "./vendor/three/examples/jsm/postprocessing/RenderTransitionPass.js",
  "./vendor/three/examples/jsm/postprocessing/SAOPass.js",
  "./vendor/three/examples/jsm/postprocessing/SMAAPass.js",
  "./vendor/three/examples/jsm/postprocessing/SSAARenderPass.js",
  "./vendor/three/examples/jsm/postprocessing/SSAOPass.js",
  "./vendor/three/examples/jsm/postprocessing/SSRPass.js",
  "./vendor/three/examples/jsm/postprocessing/SavePass.js",
  "./vendor/three/examples/jsm/postprocessing/ShaderPass.js",
  "./vendor/three/examples/jsm/postprocessing/TAARenderPass.js",
  "./vendor/three/examples/jsm/postprocessing/TexturePass.js",
  "./vendor/three/examples/jsm/postprocessing/UnrealBloomPass.js",
  "./vendor/three/examples/jsm/shaders/ACESFilmicToneMappingShader.js",
  "./vendor/three/examples/jsm/shaders/AfterimageShader.js",
  "./vendor/three/examples/jsm/shaders/BasicShader.js",
  "./vendor/three/examples/jsm/shaders/BleachBypassShader.js",
  "./vendor/three/examples/jsm/shaders/BlendShader.js",
  "./vendor/three/examples/jsm/shaders/BokehShader.js",
  "./vendor/three/examples/jsm/shaders/BokehShader2.js",
  "./vendor/three/examples/jsm/shaders/BrightnessContrastShader.js",
  "./vendor/three/examples/jsm/shaders/ColorCorrectionShader.js",
  "./vendor/three/examples/jsm/shaders/ColorifyShader.js",
  "./vendor/three/examples/jsm/shaders/ConvolutionShader.js",
  "./vendor/three/examples/jsm/shaders/CopyShader.js",
  "./vendor/three/examples/jsm/shaders/DOFMipMapShader.js",
  "./vendor/three/examples/jsm/shaders/DepthLimitedBlurShader.js",
  "./vendor/three/examples/jsm/shaders/DigitalGlitch.js",
  "./vendor/three/examples/jsm/shaders/DotScreenShader.js",
  "./vendor/three/examples/jsm/shaders/ExposureShader.js",
  "./vendor/three/examples/jsm/shaders/FXAAShader.js",
  "./vendor/three/examples/jsm/shaders/FilmShader.js",
  "./vendor/three/examples/jsm/shaders/FocusShader.js",
  "./vendor/three/examples/jsm/shaders/FreiChenShader.js",
  "./vendor/three/examples/jsm/shaders/GTAOShader.js",
  "./vendor/three/examples/jsm/shaders/GammaCorrectionShader.js",
  "./vendor/three/examples/jsm/shaders/HalftoneShader.js",
  "./vendor/three/examples/jsm/shaders/HorizontalBlurShader.js",
  "./vendor/three/examples/jsm/shaders/HorizontalTiltShiftShader.js",
  "./vendor/three/examples/jsm/shaders/HueSaturationShader.js",
  "./vendor/three/examples/jsm/shaders/KaleidoShader.js",
  "./vendor/three/examples/jsm/shaders/LuminosityHighPassShader.js",
  "./vendor/three/examples/jsm/shaders/LuminosityShader.js",
  "./vendor/three/examples/jsm/shaders/MirrorShader.js",
  "./vendor/three/examples/jsm/shaders/NormalMapShader.js",
  "./vendor/three/examples/jsm/shaders/OutputShader.js",
  "./vendor/three/examples/jsm/shaders/PoissonDenoiseShader.js",
  "./vendor/three/examples/jsm/shaders/RGBShiftShader.js",
  "./vendor/three/examples/jsm/shaders/SAOShader.js",
  "./vendor/three/examples/jsm/shaders/SMAAShader.js",
  "./vendor/three/examples/jsm/shaders/SSAOShader.js",
  "./vendor/three/examples/jsm/shaders/SSRShader.js",
  "./vendor/three/examples/jsm/shaders/SepiaShader.js",
  "./vendor/three/examples/jsm/shaders/SobelOperatorShader.js",
  "./vendor/three/examples/jsm/shaders/SubsurfaceScatteringShader.js",
  "./vendor/three/examples/jsm/shaders/TechnicolorShader.js",
  "./vendor/three/examples/jsm/shaders/ToonShader.js",
  "./vendor/three/examples/jsm/shaders/TriangleBlurShader.js",
  "./vendor/three/examples/jsm/shaders/UnpackDepthRGBAShader.js",
  "./vendor/three/examples/jsm/shaders/VelocityShader.js",
  "./vendor/three/examples/jsm/shaders/VerticalBlurShader.js",
  "./vendor/three/examples/jsm/shaders/VerticalTiltShiftShader.js",
  "./vendor/three/examples/jsm/shaders/VignetteShader.js",
  "./vendor/three/examples/jsm/shaders/VolumeShader.js",
  "./vendor/three/examples/jsm/shaders/WaterRefractionShader.js",
];
// <<< PRECACHE-MANIFEST

// ---------------------------------------------------------------------------
// INSTALL — precache the full manifest, then activate immediately.
//
// Per-entry semantics (each wrapped in try/catch — best-effort, a single 404
// never aborts installation, but every outcome is COUNTED and reported):
//   - network-first classes (HTML, ./js/, ./data/, root files): ALWAYS
//     refetched, so every SW update refreshes all code+data in the cache —
//     including files the page never requests at boot. Closes the placebo
//     hole where a lazily-fetched JSON stayed stale forever offline.
//   - cache-first classes (./vendor/, ./textures/): skipped when already
//     stored. Immutable by contract; editing one requires a CACHE_NAME bump.
//     This keeps the ~tens-of-MB texture set from being re-downloaded on
//     every deploy by every returning client.
// ---------------------------------------------------------------------------
const PRECACHE_CONCURRENCY = 8;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE_NAME);
      const counts = { fetched: 0, present: 0, failed: 0 };
      const queue = PRECACHE_URLS.slice();
      const worker = async () => {
        for (;;) {
          const url = queue.shift();
          if (url === undefined) return;
          try {
            const abs = new URL(url, self.location.href);
            if (isCacheFirstURL(abs) && await cache.match(abs.href)) {
              counts.present += 1;
              continue;
            }
            // cache:'no-cache' revalidates through any HTTP cache in the way
            // (GitHub Pages' 10-min cache, Safari heuristics) — the wire must
            // hand out the freshest build (Ipad.md §2.4, wire-first).
            const resp = await fetch(new Request(url, { cache: 'no-cache' }));
            if (!resp || !resp.ok) throw new Error('HTTP ' + (resp ? resp.status : 'null'));
            await cache.put(url, resp);
            counts.fetched += 1;
          } catch (err) {
            counts.failed += 1;
            // eslint-disable-next-line no-console
            console.warn('[SW] pre-cache miss for', url, err);
          }
        }
      };
      await Promise.all(Array.from({ length: PRECACHE_CONCURRENCY }, worker));
      // REPORT — the install-burst count is the offline-permanence witness.
      // eslint-disable-next-line no-console
      console.info(
        `[SW] precache ${CACHE_NAME} (build ${PRECACHE_BUILD}): ` +
        `${PRECACHE_URLS.length} entries — ${counts.fetched} fetched, ` +
        `${counts.present} already cached, ${counts.failed} failed`
      );
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn('[SW] install error:', err);
    }
    await self.skipWaiting();
  })());
});

// ---------------------------------------------------------------------------
// ACTIVATE — claim clients, evict stale caches.
// ---------------------------------------------------------------------------
self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    try {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      );
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn('[SW] activate cleanup error:', err);
    }
    await self.clients.claim();
  })());
});

// ---------------------------------------------------------------------------
// FETCH — route based on request URL + headers.
// ---------------------------------------------------------------------------

/** Is this an HTML navigation? */
function isHTMLRequest(request) {
  if (request.mode === 'navigate') return true;
  const accept = request.headers.get('accept') || '';
  return accept.includes('text/html');
}

/** Is this a JS module fetch? */
function isJSRequest(url) {
  const p = url.pathname.toLowerCase();
  return p.endsWith('.js') || p.endsWith('.mjs');
}

/** Should this URL be served cache-first? */
function isCacheFirstURL(url) {
  if (url.pathname.includes('/vendor/')) return true;
  if (url.pathname.includes('/textures/')) return true;
  return false;
}

/**
 * Curated JSON under ./data/ — small, and edited far more often than the code
 * that reads it. These are deliberately NOT cache-first: a cache-first entry is
 * pinned until CACHE_NAME changes, so every content edit silently kept serving
 * the previously cached copy and a shipped data change could never reach a
 * returning player (a city label added to data/cities.json stayed invisible
 * through any number of reloads). Network-first keeps them fresh when online
 * and still falls back to the cached copy offline, so offline-first holds.
 */
function isDataURL(url) {
  return url.pathname.includes('/data/');
}

/** Synthetic offline response when both network and cache fail. */
function offlineResponse(url) {
  return new Response(
    `// [SW] offline — ${url.href} not available\n`,
    {
      status: 503,
      statusText: 'Offline',
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    }
  );
}

/**
 * Network-first: try the network, populate cache on success, fall back to
 * cache on failure, then a synthetic offline Response.
 *
 * The network fetch is bounded by a short AbortController timeout ONLY when
 * the browser reports itself offline (`!navigator.onLine`), so a dead-but-
 * connected network (captive portal, VPN with no upstream) falls back to
 * cache fast instead of blocking on the OS socket timeout. When online, the
 * fetch is unbounded so a slow-but-healthy connection still gets the latest
 * deploy rather than being force-aborted into a stale cached copy. On
 * localhost this never trips; it's insurance for remote deploys.
 *
 * IMPORTANT: clone the response BEFORE handing it to the page; `cache.put`
 * consumes the clone's body, not the original.
 */
const NETWORK_TIMEOUT_MS = 4000;

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  // Only arm the abort timer when the browser thinks it's offline — avoids
  // aborting a slow-but-online fetch and serving stale code (see comment above).
  const controller = new AbortController();
  const timer = (typeof navigator !== 'undefined' && navigator.onLine === false)
    ? setTimeout(() => controller.abort(), NETWORK_TIMEOUT_MS)
    : null;
  try {
    const networkResponse = await fetch(request, { signal: controller.signal });
    if (networkResponse && networkResponse.ok) {
      // Clone first — do NOT await put before returning to the page.
      const copy = networkResponse.clone();
      cache.put(request, copy).catch(() => { /* ignore quota / opaque errors */ });
    }
    return networkResponse;
  } catch (_err) {
    const cached = await cache.match(request);
    if (cached) return cached;
    // Offline fallback for a version-stamped miss (x.json?v=N, core/dataUrl.js):
    // answer from the BARE precached entry, which THIS install refreshed — NOT
    // from an older stamped copy. cache.match(…, {ignoreSearch}) returns the
    // OLDEST-inserted match, so a stale x.json?v=(N-1) left by a prior online
    // session would outrank the fresh bare entry (every install cache.puts the
    // bare URL, which delete-appends it to the END of the match list). So strip
    // the query and EXACT-match the bare URL first; only then fall back to any
    // match so an unknown-query resource still resolves offline. This also lets
    // `/?shot=1`-style navigations reuse the precached './'.
    const bareURL = new URL(request.url);
    bareURL.search = '';
    const fresh = await cache.match(bareURL.href);
    if (fresh) return fresh;
    const loose = await cache.match(request, { ignoreSearch: true });
    if (loose) return loose;
    return offlineResponse(new URL(request.url));
  } finally {
    if (timer !== null) clearTimeout(timer);
  }
}

/**
 * Cache-first: serve from cache if present, otherwise fetch from network
 * and populate cache on success. Only response.ok responses are stored to
 * avoid poisoning the cache.
 */
async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) return cached;

  try {
    const networkResponse = await fetch(request);
    if (networkResponse && networkResponse.ok) {
      const copy = networkResponse.clone();
      cache.put(request, copy).catch(() => { /* ignore */ });
    }
    return networkResponse;
  } catch (_err) {
    // Same bare-URL-first fallback as networkFirst. Vendor/textures are never
    // query-stamped, so the bare match usually equals the request; kept
    // identical so the two routes can't drift in their offline semantics.
    const bareURL = new URL(request.url);
    bareURL.search = '';
    const fresh = await cache.match(bareURL.href);
    if (fresh) return fresh;
    const loose = await cache.match(request, { ignoreSearch: true });
    if (loose) return loose;
    return offlineResponse(new URL(request.url));
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Non-GET requests bypass the SW entirely.
  if (request.method !== 'GET') return;

  let url;
  try {
    url = new URL(request.url);
  } catch (_err) {
    return; // malformed URL — let the browser handle it.
  }

  // Don't intercept the SW's own URL.
  if (url.pathname.endsWith('/sw.js')) return;

  // Only handle http(s) — skip chrome-extension://, data:, blob:, etc.
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return;

  // Cache-first: vendored Three.js (./vendor/) and textures — immutable blobs.
  // This MUST be checked before the JS network-first branch below, otherwise
  // vendored `.js` modules would match isJSRequest() and go network-first.
  if (isCacheFirstURL(url)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  // Network-first: HTML navigations, JS modules, and ./data/ JSON (so new
  // deploys and content edits take effect on the next visit; falls back to
  // cache, then a synthetic offline Response).
  if (isHTMLRequest(request) || isJSRequest(url) || isDataURL(url)) {
    event.respondWith(networkFirst(request));
    return;
  }

  // Anything else — passthrough (don't call respondWith).
});
